import can
import pytest
from io import StringIO
from custom_trc_reader import CustomTRCReader  # replace with actual module name


def test_init():
    reader = CustomTRCReader(StringIO())
    assert isinstance(reader, CustomTRCReader)


def test_iter():
    reader = CustomTRCReader(StringIO(""";$FILEVERSION=2.0
;$STARTTIME=45427.5943346644
;$COLUMNS=N,O,T,I,d,l,D
;
;   Start time: 5/15/2024 14:15:50.515.0
;   Generated by PCAN-View v5.0.4.860
;   Message   Time    Type ID     Rx/Tx
;   Number    Offset  |    [hex]  |  Data Length
;   |         [ms]    |    |      |  |  Data [hex] ...
;   |         |       |    |      |  |  |
;---+-- ------+------ +- --+----- +- +- +- +- -- -- -- -- -- -- --
      1      1453.159 FD     0716 Rx 1  05 
      2      1850.303 FD     0715 Rx 1  05"""))
    messages = list(reader)
    assert all(isinstance(msg, can.Message) for msg in messages)
    assert len(messages) == 2
    messages[0].equals(can.Message(timestamp=1453.159, arbitration_id=0x716, is_extended_id=False,
                                   dlc=1, data=[0x5], is_fd=True, bitrate_switch=False,
                                   error_state_indicator=False, check=True))
    messages[1].equals(can.Message(timestamp=1850.303, arbitration_id=0x715, is_extended_id=False,
                                   dlc=1, data=[0x5], is_fd=True, bitrate_switch=False,
                                   error_state_indicator=False, check=True))
